module.exports = [
  // Zone A — 15 slots
  { id: 1,  zone: 'A', occupied: false },
  { id: 2,  zone: 'A', occupied: false },
  { id: 3,  zone: 'A', occupied: false },
  { id: 4,  zone: 'A', occupied: false },
  { id: 5,  zone: 'A', occupied: false },
  { id: 6,  zone: 'A', occupied: false },
  { id: 7,  zone: 'A', occupied: false },
  { id: 8,  zone: 'A', occupied: false },
  { id: 9,  zone: 'A', occupied: false },
  { id: 10, zone: 'A', occupied: false },
  { id: 11, zone: 'A', occupied: false },
  { id: 12, zone: 'A', occupied: false },
  { id: 13, zone: 'A', occupied: false },
  { id: 14, zone: 'A', occupied: false },
  { id: 15, zone: 'A', occupied: false },
  // Zone B — 12 slots
  { id: 16, zone: 'B', occupied: false },
  { id: 17, zone: 'B', occupied: false },
  { id: 18, zone: 'B', occupied: false },
  { id: 19, zone: 'B', occupied: false },
  { id: 20, zone: 'B', occupied: false },
  { id: 21, zone: 'B', occupied: false },
  { id: 22, zone: 'B', occupied: false },
  { id: 23, zone: 'B', occupied: false },
  { id: 24, zone: 'B', occupied: false },
  { id: 25, zone: 'B', occupied: false },
  { id: 26, zone: 'B', occupied: false },
  { id: 27, zone: 'B', occupied: false },
  // Zone C — 8 slots
  { id: 28, zone: 'C', occupied: false },
  { id: 29, zone: 'C', occupied: false },
  { id: 30, zone: 'C', occupied: false },
  { id: 31, zone: 'C', occupied: false },
  { id: 32, zone: 'C', occupied: false },
  { id: 33, zone: 'C', occupied: false },
  { id: 34, zone: 'C', occupied: false },
  { id: 35, zone: 'C', occupied: false },
];
